# Generated by Django 4.2 on 2023-10-15 05:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Identifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.URLField(max_length=100)),
                ('value', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[1-9][0-9]*$')])),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('patient', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[1-9][0-9]{9}$')])),
                ('practitioner', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[1-9][0-9]{9}$')])),
                ('organization', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[1-9][0-9]{9}$')])),
                ('identifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.identifier')),
            ],
        ),
    ]
